# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, unique=True, verbose_name='密码')),
                ('is_superuser', models.SmallIntegerField(choices=[(0, '超级管理员'), (1, '普通用户')], default=1, verbose_name='超级用户')),
                ('is_active', models.SmallIntegerField(choices=[(1, '在线'), (2, '离线'), (3, '隐身')], default=2, verbose_name='状态')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('male', ' 男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'ordering': ['c_time'],
            },
        ),
    ]
